name: Build STB_Interposer_Release

on:
  workflow_dispatch

jobs:
  build_STB_Interposer_Release:
    name: Build STB_Interposer_Release
    uses: ./.github/workflows/skyworks_evb_build.yaml
    with:
      targetName: 'STB_Interposer'
      buildType: 'MinSizeRel'
