name: Build SKY_TC_EEVB_Debug

on:
  workflow_dispatch

jobs:
  build_SKY_TC_EEVB_Debug:
    name: Build SKY_TC_EEVB_Debug
    uses: ./.github/workflows/skyworks_evb_build.yaml
    with:
      targetName: 'SKY_TC_EEVB_Debug'
